### PR TITLE
fix: invalid interface reference in d.ts

### LINKED ISSUE #22: Cannot find name 'CustomMatcherResult'
Getting the following error when trying to build a project that references v0.5.0

```
node_modules/jest-file-snapshot/index.d.ts:9:6 - error TS2304: Cannot find name 'CustomMatcherResult'.

9 ) => CustomMatcherResult;
       ~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

### PR DESCRIPTION
**Pull request by DylanPiercey**
This resolves #22

### CODE REVIEW

**Review by ggomez91 — APPROVED** [review]
This looks fine

**Review by ggomez91 — APPROVED** [review]

**Comment by ggomez91** [comment]
What is needed to merge this? I don't know CircleCI

**Comment by markwhitfeld** [comment]
Came across this too. What needs to happen to get it merged?

**Review by satya164 — APPROVED** [review]
Thanks

**Pull request merged**
